--------------------------------------------------------
--  File created - Friday-November-03-2017   
--------------------------------------------------------
REM INSERTING into PM_FSM_RULES
SET DEFINE OFF;
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (1,1,'2','kfmcasio1','PAINT_LINE_START_DATE','Motorla FX7500 Static Reader A.1');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (2,2,'2','kfmcasio2','PAINT_LINE_END_DATE','This static unit is to be replaced by new handheld unit (CR)');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (3,2,'3','kfmcasio3','TRACTOR_LINE_START_DATE','This static unit is to be replaced by new handheld unit (CR)');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (4,3,'5','kfmrfidc4','REWORK_BEFORE_MQ_START_DATE','END trigger is Pokayokeb4');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (5,6,'6','kfmrfidc3','REWORK_AFTER_MQ_END_DATE','Nordic Merlin SCANNER_ID KFMRFIDC3');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (6,4,'6','kfmrfidc3','REWORK_AFTER_MQ_END_DATE','Nordic Merlin SCANNER_ID KFMRFIDC3');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (7,4,'6','kfmrfidc2','REWORK_AFTER_MQ_START_DATE','Nordic Merlin SCANNER_ID KFMRFIDC3');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (8,7,'8','kfmrfidc1','INSPECTION_START_DATE','Nordic Merlin SCANNER_ID KFMRFIDC1');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (9,8,'8','kfmrfidc1','INSPECTION_END_DATE','INSPECTION_END_DATE comes from SAP not FSM -- RULE IS TO KEEP FSM IN STATE 8 i.e INSPECTION');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (10,9,'9','kfmrfidc1','REWORK_DUR_INSP_START_DATE','REWORK DURING INSPECTION COME FROM SAP -- RULE IS TO IGNORE IS SCANNER USED (ONLY C3 CAN EXIT REWORK_INSP_STATE 9)');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (11,9,'10','kfmrfidc3','REWORK_DUR_INSP_END_DATE','Nordic Merlin SCANNER_ID KFMRFIDC3');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (12,11,'12','kfmrfida4','SHIPPING_STATUS','Motorla FX7500 Static Reader A.4');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (13,12,'11','kfmrfida4','SHIPPING_STATUS','Motorla FX7500 Static Reader A.4');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (14,12,'14','kfmrfida6','SHIPPING_STATUS','Motorla FX7500 Static Reader A.6');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (15,12,'13','kfmrfida5','SHIPPING_STATUS','Motorla FX7500 Static Reader A.5');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (16,3,'4','250311','MQ_LINE_START_DATE','ECU init');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (17,5,'4','250311','MQ_LINE_START_DATE','ECU init');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (18,4,'4','250601','MQ_LINE_END_DATE','MQ Results');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (19,0,'1','201301','CHASSIS_LINE_START_DATE','PokaYoke Engine (Chassis Start trigger)');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (20,1,'1','201601','CHASSIS_LINE_END_DATE','Chassis Results');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (21,3,'3','245601','TRACTOR_LINE_END_DATE','Line Off Result');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (22,6,'4','250311','MQ_LINE_START_DATE','ECU init');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (23,12,'14','kfmrfida7','SHIPPING_STATUS','Motorla FX7500 Static Reader A.7  additional unit / antenna ');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (24,13,'12','kfmrfida6','SHIPPING_STATUS','Motorla FX7500 Static Reader A.9 from future area to outside area CHECK RSSI!!!');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (25,5,'5','kfmrfidc3','REWORK_BEFORE_MQ_END_DATE',' TBC Temporarily using RFIDC3 to test');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (26,6,'7','250601','MQ_LINE_END_DATE','MQ Results');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (27,4,'7','250701','PRODUCTION_END_DATE','MFG');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (27,6,'7','250701','PRODUCTION_END_DATE','Production End');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (29,11,'12','kfmrfida8','SHIPPING_STATUS','Motorla FX7500 Static Reader A.4/A.8');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (30,12,'11','kfmrfida8','SHIPPING_STATUS','Motorla FX7500 Static Reader A.4/A.8');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (31,12,'13','kfmrfida9','SHIPPING_STATUS','Motorla FX7500 Static Reader A.5/A.9');
Insert into PM_FSM_RULES (RULENO,CURRENTSTATE,NEXTSTATE,SCANNER_ID,EVENT_RAISED_DATECOLUMN,RULE_COMMENT) values (32,13,'12','kfmrfida9','SHIPPING_STATUS','Motorla FX7500 Static Reader A.5/A.9');

