--------------------------------------------------------
--  DDL for Table PM_RFID_RAW_EVENTS
--------------------------------------------------------

  CREATE TABLE "HUBADMIN"."PM_RFID_RAW_EVENTS" 
   (	"SCAN_TIMESTAMP" DATE, 
	"TAGID" VARCHAR2(24 BYTE), 
	"IDNO" VARCHAR2(9 BYTE), 
	"SCANNER_IP" VARCHAR2(15 BYTE), 
	"RSSI" NUMBER(3,0), 
	"SCANNER_ID" VARCHAR2(17 BYTE), 
	"SCANNER_TYPE" NUMBER(1,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 6291456 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KBTDBDAT" ;

   COMMENT ON COLUMN "HUBADMIN"."PM_RFID_RAW_EVENTS"."SCAN_TIMESTAMP" IS 'Scan Timestamp';
   COMMENT ON COLUMN "HUBADMIN"."PM_RFID_RAW_EVENTS"."TAGID" IS 'Tag EPC';
   COMMENT ON COLUMN "HUBADMIN"."PM_RFID_RAW_EVENTS"."IDNO" IS 'Tractor ID No';
   COMMENT ON COLUMN "HUBADMIN"."PM_RFID_RAW_EVENTS"."SCANNER_IP" IS 'Scanner IP Address';
   COMMENT ON COLUMN "HUBADMIN"."PM_RFID_RAW_EVENTS"."RSSI" IS 'Signal Strength';
