--------------------------------------------------------
--  DDL for Table PROD_MONITOR_PARTS
--------------------------------------------------------

  CREATE TABLE "HUBADMIN"."PROD_MONITOR_PARTS" 
   (	"ID_NO" NCHAR(9), 
	"SEQ_NO" NUMBER(4,0), 
	"LOCATION" NCHAR(4), 
	"CALCULATED_DATE" DATE, 
	"ITEM_NUMBER" NCHAR(10), 
	"ITEM_DESCRIPTION" NVARCHAR2(30), 
	"REQUIREMENT_QTY" NUMBER(3,0), 
	"MISSING_QTY" NUMBER(3,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KBTDBDAT" ;
