--------------------------------------------------------
--  Constraints for Table PROD_MONITOR
--------------------------------------------------------

  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("PLAN_PROD_FINISH_DATE" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("MODEL_CODE" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("MONTHLY_SEQ" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("UPDATE_BY" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("CREATE_BY" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR" MODIFY ("ID_NO" NOT NULL ENABLE);
