--------------------------------------------------------
--  Constraints for Table PROD_MONITOR_COMMENT
--------------------------------------------------------

  ALTER TABLE "HUBADMIN"."PROD_MONITOR_COMMENT" ADD CONSTRAINT "PROD_MONITOR_COMMENT_PK" PRIMARY KEY ("ID_NO", "SEQ_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KBTDBIDX"  ENABLE;
  ALTER TABLE "HUBADMIN"."PROD_MONITOR_COMMENT" MODIFY ("UPDATE_BY" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR_COMMENT" MODIFY ("UPDATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR_COMMENT" MODIFY ("CREATE_BY" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR_COMMENT" MODIFY ("CREATE_DATE" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR_COMMENT" MODIFY ("SEQ_NO" NOT NULL ENABLE);
  ALTER TABLE "HUBADMIN"."PROD_MONITOR_COMMENT" MODIFY ("ID_NO" NOT NULL ENABLE);
