--------------------------------------------------------
--  DDL for Index PROD_MONITOR_COMMENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HUBADMIN"."PROD_MONITOR_COMMENT_PK" ON "HUBADMIN"."PROD_MONITOR_COMMENT" ("ID_NO", "SEQ_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 3145728 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "KBTDBIDX" ;
