--------------------------------------------------------
--  DDL for Trigger SCANNER_ID_LOOKUP
--------------------------------------------------------

  CREATE OR REPLACE TRIGGER "HUBADMIN"."SCANNER_ID_LOOKUP" 
BEFORE INSERT ON PM_RFID_RAW_EVENTS 
FOR EACH ROW
BEGIN
 IF (:new.SCANNER_TYPE = 1) THEN
  SELECT SCANNER_ID INTO :new.SCANNER_ID FROM PM_DEVICE_MAP 
  WHERE SCANNER_IP = :new.SCANNER_ID;
  END IF;
END;
/
ALTER TRIGGER "HUBADMIN"."SCANNER_ID_LOOKUP" ENABLE;
